---
abstract: 'extended simple IRC bot for pluggable modules'
author:
  - 'Mario Domgoergen <mdom@cpan.org>'
build_requires:
  FindBin: 0
  Module::Build: 0.3601
  Test::More: 0
  Test::Perl::Critic: 0
  Test::PerlTidy: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
  Module::Build: 0.3601
generated_by: 'Dist::Zilla version 2.100880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bot-BasicBot-Pluggable
requires:
  Bot::BasicBot: 0.60
  CGI: 0
  Carp: 0
  Config::Find: 0
  DBI: 0
  DBM::Deep: 0
  Data::Dumper: 0
  File::Copy: 0
  File::Spec: 0
  File::Temp: 0
  LWP::UserAgent: 0
  List::MoreUtils: 0
  Log::Log4perl: 0
  Log::Log4perl::Level: 0
  Module::Load: 0
  Module::Pluggable: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Getopt::Dashes: 0
  MooseX::SimpleConfig: 0
  POE: 0
  Socket: 0
  Storable: 0
  Test::Builder::Module: 0
  Text::Unidecode: 0
  Try::Tiny: 0
  URI: 0
  URI::Find::Simple: 0
  URI::Title: 0
  XML::Feed: 0
  perl: 5.8.0
version: 0.87
