---
name: Bot-BasicBot-Pluggable
version: 0.80
author:
  - 'Mario Domgoergen <mdom@cpan.org>'
abstract: extended simple IRC bot for pluggable modules
license: perl
resources:
  license: ~
  repository: http://github.com/mdom/bot-basicbot-pluggable
requires:
  Bot::BasicBot: 0.30
  Config::Find: 0
  DBD::SQLite: 0
  DBI: 0
  DBM::Deep: 0
  Getopt::Long: 0
  LWP::UserAgent: 0
  List::MoreUtils: 0
  Module::Pluggable: 0
  Moose: 0
  MooseX::Getopt: 0
  MooseX::SimpleConfig: 0
  Test::More: 0.01
  Text::Unidecode: 0
  URI::Find::Simple: 0
  URI::Title: 0.1
  perl: 5.8.0
recommends:
  XML::Feed: 0
provides:
  App::Bot::BasicBot::Pluggable:
    file: lib/App/Bot/BasicBot/Pluggable.pm
  Bot::BasicBot::Pluggable:
    file: lib/Bot/BasicBot/Pluggable.pm
    version: 0.80
  Bot::BasicBot::Pluggable::Module:
    file: lib/Bot/BasicBot/Pluggable/Module.pm
  Bot::BasicBot::Pluggable::Module::Auth:
    file: lib/Bot/BasicBot/Pluggable/Module/Auth.pm
  Bot::BasicBot::Pluggable::Module::Base:
    file: lib/Bot/BasicBot/Pluggable/Module/Base.pm
  Bot::BasicBot::Pluggable::Module::DNS:
    file: lib/Bot/BasicBot/Pluggable/Module/DNS.pm
  Bot::BasicBot::Pluggable::Module::Google:
    file: lib/Bot/BasicBot/Pluggable/Module/Google.pm
  Bot::BasicBot::Pluggable::Module::Infobot:
    file: lib/Bot/BasicBot/Pluggable/Module/Infobot.pm
  Bot::BasicBot::Pluggable::Module::Join:
    file: lib/Bot/BasicBot/Pluggable/Module/Join.pm
  Bot::BasicBot::Pluggable::Module::Karma:
    file: lib/Bot/BasicBot/Pluggable/Module/Karma.pm
  Bot::BasicBot::Pluggable::Module::Loader:
    file: lib/Bot/BasicBot/Pluggable/Module/Loader.pm
  Bot::BasicBot::Pluggable::Module::Seen:
    file: lib/Bot/BasicBot/Pluggable/Module/Seen.pm
  Bot::BasicBot::Pluggable::Module::Title:
    file: lib/Bot/BasicBot/Pluggable/Module/Title.pm
  Bot::BasicBot::Pluggable::Module::Vars:
    file: lib/Bot/BasicBot/Pluggable/Module/Vars.pm
  Bot::BasicBot::Pluggable::Store:
    file: lib/Bot/BasicBot/Pluggable/Store.pm
  Bot::BasicBot::Pluggable::Store::DBI:
    file: lib/Bot/BasicBot/Pluggable/Store/DBI.pm
  Bot::BasicBot::Pluggable::Store::Deep:
    file: lib/Bot/BasicBot/Pluggable/Store/Deep.pm
  Bot::BasicBot::Pluggable::Store::Memory:
    file: lib/Bot/BasicBot/Pluggable/Store/Memory.pm
  Bot::BasicBot::Pluggable::Store::Storable:
    file: lib/Bot/BasicBot/Pluggable/Store/Storable.pm
  Test::Bot::BasicBot::Pluggable:
    file: lib/Test/Bot/BasicBot/Pluggable.pm
    version: 0.1
  Test::Bot::BasicBot::Pluggable::Store:
    file: lib/Test/Bot/BasicBot/Pluggable/Store.pm
    version: 0.1
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
