---
name: Bot-BasicBot-Pluggable
version: 0.60
author:
  - 'Tom Insam <tom@jerakeen.org>'
abstract: extended simple IRC bot for pluggable modules
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Bot::BasicBot: 0.30
  DBD::SQLite: 0
  DBI: 0
  DBM::Deep: 0
  Getopt::Long: 0
  Test::More: 0.01
  Text::Unidecode: 0
  URI::Find::Simple: 0
  URI::Title: 0.1
  perl: 5.8.0
recommends:
  XML::Feed: 0
provides:
  Bot::BasicBot::Pluggable:
    file: lib/Bot/BasicBot/Pluggable.pm
    version: 0.60
  Bot::BasicBot::Pluggable::Module:
    file: lib/Bot/BasicBot/Pluggable/Module.pm
  Bot::BasicBot::Pluggable::Module::Auth:
    file: lib/Bot/BasicBot/Pluggable/Module/Auth.pm
  Bot::BasicBot::Pluggable::Module::Base:
    file: lib/Bot/BasicBot/Pluggable/Module/Base.pm
  Bot::BasicBot::Pluggable::Module::DNS:
    file: lib/Bot/BasicBot/Pluggable/Module/DNS.pm
  Bot::BasicBot::Pluggable::Module::Google:
    file: lib/Bot/BasicBot/Pluggable/Module/Google.pm
  Bot::BasicBot::Pluggable::Module::Infobot:
    file: lib/Bot/BasicBot/Pluggable/Module/Infobot.pm
  Bot::BasicBot::Pluggable::Module::Join:
    file: lib/Bot/BasicBot/Pluggable/Module/Join.pm
  Bot::BasicBot::Pluggable::Module::Karma:
    file: lib/Bot/BasicBot/Pluggable/Module/Karma.pm
  Bot::BasicBot::Pluggable::Module::Loader:
    file: lib/Bot/BasicBot/Pluggable/Module/Loader.pm
  Bot::BasicBot::Pluggable::Module::Seen:
    file: lib/Bot/BasicBot/Pluggable/Module/Seen.pm
  Bot::BasicBot::Pluggable::Module::Title:
    file: lib/Bot/BasicBot/Pluggable/Module/Title.pm
  Bot::BasicBot::Pluggable::Module::Vars:
    file: lib/Bot/BasicBot/Pluggable/Module/Vars.pm
  Bot::BasicBot::Pluggable::Store:
    file: lib/Bot/BasicBot/Pluggable/Store.pm
  Bot::BasicBot::Pluggable::Store::DBI:
    file: lib/Bot/BasicBot/Pluggable/Store/DBI.pm
  Bot::BasicBot::Pluggable::Store::Deep:
    file: lib/Bot/BasicBot/Pluggable/Store/Deep.pm
  Bot::BasicBot::Pluggable::Store::Storable:
    file: lib/Bot/BasicBot/Pluggable/Store/Storable.pm
generated_by: Module::Build version 0.31
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
